<section id="general"
    <?php if ( $tab != 'general' ) : ?>style="display: none;"<?php endif ?>
>
    <h3>
        <?php _e( 'General', 'inquiry' ) ?>
    </h3>

    <table class="form-table">

        <tr valign="top">
            <th scope="row"><?php _e( 'Title format', 'inquiry' ) ?></th>
            <td>
                <input type="text"
                    name="title_format"
                    class="regular-text"
                    placeholder="<?php _e( 'F j, Y H:i', 'inquiry' ) ?>"
                    value="<?php echo $inquiry->title_format ?>"
                />
                <br>
                <span class="description">
                    <?php _e( 'Date format applied as inquiry title.', 'inquiry' ) ?>
                </span>
                <br>
                <span class="description">
                    <?php _e( 'Use php formatting:', 'SocialFeeder' ) ?> 
                    <a href="http://php.net/manual/en/function.date.php">
                        <?php _e( 'PHP dates', 'SocialFeeder' ) ?>
                    </a>
                </span>
            </td>
        </tr>

    </table>

    <table class="form-table">

        <h4>
            <?php _e( 'Notifications', 'inquiry' ) ?>
        </h4>

        <tr valign="top">
            <th scope="row"><?php _e( 'Notify by email', 'inquiry' ) ?></th>
            <td>
                <input type="checkbox"
                    name="is_notification_enabled"
                    value="1"
                    <?php if ( $inquiry->is_notification_enabled ) : ?>checked<?php endif ?>
                />
                <br>
                <span class="description">
                    <?php _e( 'Notifies by email any inquiry generated by forms.', 'inquiry' ) ?>
                </span>
            </td>
        </tr>

        <tr valign="top">
            <th scope="row"><?php _e( 'Notification email', 'inquiry' ) ?></th>
            <td>
                <input type="email"
                    name="notification_email"
                    class="regular-text"
                    placeholder="<?php _e( 'name@domain.com', 'inquiry' ) ?>"
                    value="<?php echo $inquiry->notification_email ?>"
                />
                <br>
                <span class="description">
                    <?php _e( 'Email to send notifications to.', 'inquiry' ) ?>
                </span>
            </td>
        </tr>

        <tr valign="top">
            <th scope="row"><?php _e( 'Notification subject', 'inquiry' ) ?></th>
            <td>
                <input type="text"
                    name="notification_subject"
                    class="regular-text"
                    value="<?php echo $inquiry->notification_subject ?>"
                />
                <br>
                <span class="description">
                    <?php _e( 'Notification email subject.', 'inquiry' ) ?>
                </span>
            </td>
        </tr>

    </table>

    <?php do_action( 'inquery_settings_general_view' ) ?>

</section>